# Workflow starts automatically on push or can be triggered manually.
# This is a desirable pattern as it allows for adhoc test runs without a code push
name: Run SAML
on: [workflow_dispatch, repository_dispatch]
env:
  SERVER_HOST: 'localhost'
  SERVER_PORT: 8080
jobs:
  spin-up-samls:
    runs-on: ubuntu-latest
    # In order for Cypress to run well, it needs to be fed the needed parameters.
    # The below is a mix of Cypress environment variables (All capital) and ones that are needed for this specific set of scripts (Mix of capital and lowercase)
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      # Checkout the PR branch
      - name: Checkout Target Branch
        uses: actions/checkout@v3

      - name: Build and Run SAML Playground
        run: |
          npm install
          yarn
          yarn build
          yarn local
        working-directory: ./examples/saml/public/node
      - name: Check Output Parameters
        run: |
          wget http://localhost:8080
          
